<template>
  <div class="css-container">
    <div class="size1">
      <div class="height36">
        <div class="loc-mc-box">
          <p class="bnj-txt txt-up">百大</p>
          <img src="../../assets/my-logo.png" alt="menuName" class="bnj-gif">
          <p class="bnj-txt txt-down">百大</p>
        </div>
      </div>
    </div>
    <!-- 心跳的效果 -->
    <div class="size1">
      <div class="height36 heartbeat">
        心跳
      </div>
    </div>
    <!-- 跳动的点 -->
    <div class="size1">
      <div class="dot-flashing"></div>
    </div>
    <div class="size1">
      <div class="dot-carousel"></div>
    </div>
    <div class="size1">
      <div class="dot-spin"></div>
    </div>
    <div class="size1">
      <div class="dot-bouncing"></div>
    </div>
    <div class="size1">
      <div class="dot-rolling"></div>
    </div>
    <!-- 抖动的猴子 -->
    <div class="size1 positionR">
      <i class="preview-item big transp shake-hard shake-constant shake-constant--hover" id="pr2">
        <span class="preview-icon">🙈</span>
      </i>
    </div>
    <div class="size1 positionR">
      <i class="preview-item big transp shake-constant shake-constant--hover shake-vertical" id="pr2">
        <span class="preview-icon">🙈</span>
      </i>
    </div>
    <div class="size1 positionR">
        <span class="rshare-qzone"></span>
    </div>
    <div class="size1 positionR">
        <a href="#" class="hvr-bubble-top">Bubble Top</a>
    </div>
    <div class="size1 positionR">
        <a href="#" class="hvr-bubble-float-top">Bubble Float Top</a>
    </div>
    <div class="size1 positionR">
        <a href="#" class="hvr-curl-top-left">Curl Top Left</a>
    </div>
  </div>
</template>

<script>
export default {
  name: "cssPage",
  data() {
    return {

    };
  },
  components: {

  },
  mounted() {
  },
  methods: {

  }
};
</script>

<style scoped lang="scss">
.size1 {
  box-shadow: 0 0.4rem 0.8rem -0.1rem rgba(0, 32, 128, .1), 0 0 0 1px #f0f2f7;
  padding: 20px;
  margin: 24px;
  background-color: #fff;
  width: 200px;
  height: 150px;
  text-align: center;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  vertical-align: top;
}
.loc-mc-box {
    width: 54px;
    height: 108px;
    overflow: hidden;
    position: relative;
    animation: locmoveclipslider 10s infinite ease-out;
    animation-delay: 1.5s;
}
.loc-mc-box .txt-up {
    position: absolute;
    left: 0;
    top: 0;
}
.loc-mc-box .bnj-gif {
    position: absolute;
    left: 0;
    top: 36px;
    width: 54px;
    height: 36px;
    transform: translateZ(0);
}
.loc-mc-box .txt-down {
    position: absolute;
    left: 0;
    top: 72px;
}
.loc-mc-box .bnj-txt {
    line-height: 36px;
    height: 36px;
    text-align: center;
    width: 100%;
    margin: 0px;
}
@keyframes locmoveclipslider {
  0% {
      transform: translateY(0);
  }
  5% {
      transform: translateY(-36px);
  }
  50% {
      transform: translateY(-36px);
  }
  55% {
      transform: translateY(-72px);
  }
  100% {
      transform: translateY(-72px);
  }
}
.height36 {
  height: 36px;
  overflow: hidden;
}
.heartbeat {
    -webkit-animation: heartbeat 1.5s ease-in-out infinite both;
    animation: heartbeat 1.5s ease-in-out infinite both;
    font-size: 16px;
    line-height: 36px;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-1-26 15:39:53
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation heartbeat
 * ----------------------------------------
 */
@-webkit-keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: center center;
            transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
            transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
            transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
            transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}
@keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: center center;
            transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
            transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
            transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
            transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}
/**
 * ==============================================
 * Dot Flashing
 * ==============================================
 */
.dot-flashing {
  position: relative;
  width: 10px;
  height: 10px;
  border-radius: 5px;
  background-color: #9880ff;
  color: #9880ff;
  animation: dot-flashing 1s infinite linear alternate;
  animation-delay: .5s;
}

.dot-flashing::before, .dot-flashing::after {
  content: '';
  display: inline-block;
  position: absolute;
  top: 0;
}

.dot-flashing::before {
  left: -15px;
  width: 10px;
  height: 10px;
  border-radius: 5px;
  background-color: #9880ff;
  color: #9880ff;
  animation: dot-flashing 1s infinite alternate;
  animation-delay: 0s;
}

.dot-flashing::after {
  left: 15px;
  width: 10px;
  height: 10px;
  border-radius: 5px;
  background-color: #9880ff;
  color: #9880ff;
  animation: dot-flashing 1s infinite alternate;
  animation-delay: 1s;
}

@keyframes dot-flashing {
  0% {
    background-color: #9880ff;
  }
  50%,
  100% {
    background-color: #ebe6ff;
  }
}
/**
 * ==============================================
 * Dot Carousel
 * ==============================================
 */
.dot-carousel {
  position: relative;
  left: -9999px;
  width: 10px;
  height: 10px;
  border-radius: 5px;
  background-color: #9880ff;
  color: #9880ff;
  box-shadow: 9984px 0 0 0 #9880ff, 9999px 0 0 0 #9880ff, 10014px 0 0 0 #9880ff;
  animation: dot-carousel 1.5s infinite linear;
}

@keyframes dot-carousel {
  0% {
    box-shadow: 9984px 0 0 -1px #9880ff, 9999px 0 0 1px #9880ff, 10014px 0 0 -1px #9880ff;
  }
  50% {
    box-shadow: 10014px 0 0 -1px #9880ff, 9984px 0 0 -1px #9880ff, 9999px 0 0 1px #9880ff;
  }
  100% {
    box-shadow: 9999px 0 0 1px #9880ff, 10014px 0 0 -1px #9880ff, 9984px 0 0 -1px #9880ff;
  }
}
/**
 * ==============================================
 * Dot Spin
 * ==============================================
 */
.dot-spin {
  position: relative;
  width: 10px;
  height: 10px;
  border-radius: 5px;
  background-color: transparent;
  color: transparent;
  box-shadow: 0 -18px 0 0 #9880ff, 12.72984px -12.72984px 0 0 #9880ff, 18px 0 0 0 #9880ff, 12.72984px 12.72984px 0 0 rgba(152, 128, 255, 0), 0 18px 0 0 rgba(152, 128, 255, 0), -12.72984px 12.72984px 0 0 rgba(152, 128, 255, 0), -18px 0 0 0 rgba(152, 128, 255, 0), -12.72984px -12.72984px 0 0 rgba(152, 128, 255, 0);
  animation: dot-spin 1.5s infinite linear;
}

@keyframes dot-spin {
  0%,
  100% {
    box-shadow: 0 -18px 0 0 #9880ff, 12.72984px -12.72984px 0 0 #9880ff, 18px 0 0 0 #9880ff, 12.72984px 12.72984px 0 -5px rgba(152, 128, 255, 0), 0 18px 0 -5px rgba(152, 128, 255, 0), -12.72984px 12.72984px 0 -5px rgba(152, 128, 255, 0), -18px 0 0 -5px rgba(152, 128, 255, 0), -12.72984px -12.72984px 0 -5px rgba(152, 128, 255, 0);
  }
  12.5% {
    box-shadow: 0 -18px 0 -5px rgba(152, 128, 255, 0), 12.72984px -12.72984px 0 0 #9880ff, 18px 0 0 0 #9880ff, 12.72984px 12.72984px 0 0 #9880ff, 0 18px 0 -5px rgba(152, 128, 255, 0), -12.72984px 12.72984px 0 -5px rgba(152, 128, 255, 0), -18px 0 0 -5px rgba(152, 128, 255, 0), -12.72984px -12.72984px 0 -5px rgba(152, 128, 255, 0);
  }
  25% {
    box-shadow: 0 -18px 0 -5px rgba(152, 128, 255, 0), 12.72984px -12.72984px 0 -5px rgba(152, 128, 255, 0), 18px 0 0 0 #9880ff, 12.72984px 12.72984px 0 0 #9880ff, 0 18px 0 0 #9880ff, -12.72984px 12.72984px 0 -5px rgba(152, 128, 255, 0), -18px 0 0 -5px rgba(152, 128, 255, 0), -12.72984px -12.72984px 0 -5px rgba(152, 128, 255, 0);
  }
  37.5% {
    box-shadow: 0 -18px 0 -5px rgba(152, 128, 255, 0), 12.72984px -12.72984px 0 -5px rgba(152, 128, 255, 0), 18px 0 0 -5px rgba(152, 128, 255, 0), 12.72984px 12.72984px 0 0 #9880ff, 0 18px 0 0 #9880ff, -12.72984px 12.72984px 0 0 #9880ff, -18px 0 0 -5px rgba(152, 128, 255, 0), -12.72984px -12.72984px 0 -5px rgba(152, 128, 255, 0);
  }
  50% {
    box-shadow: 0 -18px 0 -5px rgba(152, 128, 255, 0), 12.72984px -12.72984px 0 -5px rgba(152, 128, 255, 0), 18px 0 0 -5px rgba(152, 128, 255, 0), 12.72984px 12.72984px 0 -5px rgba(152, 128, 255, 0), 0 18px 0 0 #9880ff, -12.72984px 12.72984px 0 0 #9880ff, -18px 0 0 0 #9880ff, -12.72984px -12.72984px 0 -5px rgba(152, 128, 255, 0);
  }
  62.5% {
    box-shadow: 0 -18px 0 -5px rgba(152, 128, 255, 0), 12.72984px -12.72984px 0 -5px rgba(152, 128, 255, 0), 18px 0 0 -5px rgba(152, 128, 255, 0), 12.72984px 12.72984px 0 -5px rgba(152, 128, 255, 0), 0 18px 0 -5px rgba(152, 128, 255, 0), -12.72984px 12.72984px 0 0 #9880ff, -18px 0 0 0 #9880ff, -12.72984px -12.72984px 0 0 #9880ff;
  }
  75% {
    box-shadow: 0 -18px 0 0 #9880ff, 12.72984px -12.72984px 0 -5px rgba(152, 128, 255, 0), 18px 0 0 -5px rgba(152, 128, 255, 0), 12.72984px 12.72984px 0 -5px rgba(152, 128, 255, 0), 0 18px 0 -5px rgba(152, 128, 255, 0), -12.72984px 12.72984px 0 -5px rgba(152, 128, 255, 0), -18px 0 0 0 #9880ff, -12.72984px -12.72984px 0 0 #9880ff;
  }
  87.5% {
    box-shadow: 0 -18px 0 0 #9880ff, 12.72984px -12.72984px 0 0 #9880ff, 18px 0 0 -5px rgba(152, 128, 255, 0), 12.72984px 12.72984px 0 -5px rgba(152, 128, 255, 0), 0 18px 0 -5px rgba(152, 128, 255, 0), -12.72984px 12.72984px 0 -5px rgba(152, 128, 255, 0), -18px 0 0 -5px rgba(152, 128, 255, 0), -12.72984px -12.72984px 0 0 #9880ff;
  }
}
/**
 * ==============================================
 * Experiment: Emoji
 * Dot Bouncing
 * ==============================================
 */
.dot-bouncing {
  position: relative;
  height: 10px;
  font-size: 10px;
}

.dot-bouncing::before {
  content: '⚽🏀🏐';
  display: inline-block;
  position: relative;
  animation: dot-bouncing 1s infinite;
}

@keyframes dot-bouncing {
  0% {
    top: -20px;
    animation-timing-function: ease-in;
  }
  34% {
    transform: scale(1, 1);
  }
  35% {
    top: 20px;
    animation-timing-function: ease-out;
    transform: scale(1.5, 0.5);
  }
  45% {
    transform: scale(1, 1);
  }
  90% {
    top: -20px;
  }
  100% {
    top: -20px;
  }
}
/**
 * ==============================================
 * Experiment: Emoji
 * Dot Rolling
 * ==============================================
 */
.dot-rolling {
  position: relative;
  height: 10px;
  font-size: 10px;
}

.dot-rolling::before {
  content: '⚽';
  display: inline-block;
  position: relative;
  transform: translateX(-25px);
  animation: dot-rolling 3s infinite;
}

@keyframes dot-rolling {
  0% {
    content: '⚽';
    transform: translateX(-25px) rotateZ(0deg);
  }
  16.667% {
    content: '⚽';
    transform: translateX(25px) rotateZ(720deg);
  }
  33.333% {
    content: '⚽';
    transform: translateX(-25px) rotateZ(0deg);
  }
  34.333% {
    content: '🏀';
    transform: translateX(-25px) rotateZ(0deg);
  }
  50% {
    content: '🏀';
    transform: translateX(25px) rotateZ(720deg);
  }
  66.667% {
    content: '🏀';
    transform: translateX(-25px) rotateZ(0deg);
  }
  67.667% {
    content: '🏐';
    transform: translateX(-25px) rotateZ(0deg);
  }
  83.333% {
    content: '🏐';
    transform: translateX(25px) rotateZ(720deg);
  }
  100% {
    content: '🏐';
    transform: translateX(-25px) rotateZ(0deg);
  }
}
.shake-hard.shake-constant {
    animation-name: shake-hard;
    animation-duration: 2200ms;
    animation-timing-function: ease-in-out;
    animation-iteration-count: infinite;
    .preview-icon {
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        font-size: 70px;
        font-style: normal;
    }
}
.shake-constant.shake-constant--hover:hover {
    animation-play-state: paused;
}
@keyframes shake-hard {
    2% {
        transform: translate(7px, -4px) rotate(-.5deg)
    }

    4% {
        transform: translate(3px, 7px) rotate(2.5deg)
    }

    6% {
        transform: translate(3px, 8px) rotate(.5deg)
    }

    8% {
        transform: translate(-7px, 4px) rotate(1.5deg)
    }

    10% {
        transform: translate(6px, 10px) rotate(-.5deg)
    }

    12% {
        transform: translate(4px, 2px) rotate(-.5deg)
    }

    14% {
        transform: translate(-4px, 6px) rotate(3.5deg)
    }

    16% {
        transform: translate(1px, 5px) rotate(-1.5deg)
    }

    18% {
        transform: translate(3px, -7px) rotate(-2.5deg)
    }

    20% {
        transform: translate(-8px, -7px) rotate(.5deg)
    }

    22% {
        transform: translate(3px, -2px) rotate(-2.5deg)
    }

    24% {
        transform: translate(5px, -4px) rotate(1.5deg)
    }

    26% {
        transform: translate(-6px, -4px) rotate(-.5deg)
    }

    28% {
        transform: translate(1px, 0px) rotate(.5deg)
    }

    30% {
        transform: translate(-9px, -3px) rotate(3.5deg)
    }

    32% {
        transform: translate(3px, 6px) rotate(-1.5deg)
    }

    34% {
        transform: translate(-2px, -3px) rotate(-1.5deg)
    }

    36% {
        transform: translate(9px, -3px) rotate(-.5deg)
    }

    38% {
        transform: translate(9px, -9px) rotate(-1.5deg)
    }

    40% {
        transform: translate(8px, -7px) rotate(-2.5deg)
    }

    42% {
        transform: translate(-8px, -2px) rotate(2.5deg)
    }

    44% {
        transform: translate(-7px, 2px) rotate(-.5deg)
    }

    46% {
        transform: translate(-1px, 4px) rotate(3.5deg)
    }

    48% {
        transform: translate(3px, 1px) rotate(1.5deg)
    }

    50% {
        transform: translate(9px, -1px) rotate(2.5deg)
    }

    52% {
        transform: translate(-1px, 5px) rotate(-2.5deg)
    }

    54% {
        transform: translate(9px, -2px) rotate(.5deg)
    }

    56% {
        transform: translate(5px, -4px) rotate(-2.5deg)
    }

    58% {
        transform: translate(5px, -8px) rotate(-1.5deg)
    }

    60% {
        transform: translate(10px, 4px) rotate(1.5deg)
    }

    62% {
        transform: translate(-8px, 1px) rotate(-2.5deg)
    }

    64% {
        transform: translate(-9px, 6px) rotate(-1.5deg)
    }

    66% {
        transform: translate(-3px, 2px) rotate(.5deg)
    }

    68% {
        transform: translate(10px, 4px) rotate(.5deg)
    }

    70% {
        transform: translate(3px, -4px) rotate(-2.5deg)
    }

    72% {
        transform: translate(-5px, 10px) rotate(.5deg)
    }

    74% {
        transform: translate(1px, -7px) rotate(3.5deg)
    }

    76% {
        transform: translate(8px, -3px) rotate(-2.5deg)
    }

    78% {
        transform: translate(-8px, 2px) rotate(-.5deg)
    }

    80% {
        transform: translate(2px, 7px) rotate(-2.5deg)
    }

    82% {
        transform: translate(6px, -4px) rotate(1.5deg)
    }

    84% {
        transform: translate(3px, 2px) rotate(3.5deg)
    }

    86% {
        transform: translate(0px, -5px) rotate(-2.5deg)
    }

    88% {
        transform: translate(1px, -3px) rotate(2.5deg)
    }

    90% {
        transform: translate(-8px, -9px) rotate(2.5deg)
    }

    92% {
        transform: translate(-2px, 3px) rotate(2.5deg)
    }

    94% {
        transform: translate(-6px, 0px) rotate(-.5deg)
    }

    96% {
        transform: translate(-9px, 8px) rotate(1.5deg)
    }

    98% {
        transform: translate(9px, 4px) rotate(-1.5deg)
    }

    0%,100% {
        transform: translate(0, 0) rotate(0)
    }
}
.shake-vertical.shake-constant {
    animation-name: shake-vertical;
    animation-duration: 2200ms;
    animation-timing-function: ease-in-out;
    animation-iteration-count: infinite;
    .preview-icon {
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        font-size: 70px;
        font-style: normal;
    }
}

@keyframes shake-vertical {
    2% {
        transform: translate(0, -9px) rotate(0)
    }

    4% {
        transform: translate(0, 0px) rotate(0)
    }

    6% {
        transform: translate(0, 4px) rotate(0)
    }

    8% {
        transform: translate(0, 4px) rotate(0)
    }

    10% {
        transform: translate(0, 0px) rotate(0)
    }

    12% {
        transform: translate(0, -4px) rotate(0)
    }

    14% {
        transform: translate(0, 8px) rotate(0)
    }

    16% {
        transform: translate(0, 8px) rotate(0)
    }

    18% {
        transform: translate(0, 4px) rotate(0)
    }

    20% {
        transform: translate(0, -5px) rotate(0)
    }

    22% {
        transform: translate(0, -8px) rotate(0)
    }

    24% {
        transform: translate(0, -4px) rotate(0)
    }

    26% {
        transform: translate(0, -9px) rotate(0)
    }

    28% {
        transform: translate(0, -3px) rotate(0)
    }

    30% {
        transform: translate(0, -9px) rotate(0)
    }

    32% {
        transform: translate(0, 8px) rotate(0)
    }

    34% {
        transform: translate(0, -6px) rotate(0)
    }

    36% {
        transform: translate(0, -7px) rotate(0)
    }

    38% {
        transform: translate(0, -7px) rotate(0)
    }

    40% {
        transform: translate(0, 1px) rotate(0)
    }

    42% {
        transform: translate(0, -7px) rotate(0)
    }

    44% {
        transform: translate(0, 0px) rotate(0)
    }

    46% {
        transform: translate(0, 10px) rotate(0)
    }

    48% {
        transform: translate(0, 1px) rotate(0)
    }

    50% {
        transform: translate(0, 7px) rotate(0)
    }

    52% {
        transform: translate(0, -6px) rotate(0)
    }

    54% {
        transform: translate(0, 9px) rotate(0)
    }

    56% {
        transform: translate(0, 8px) rotate(0)
    }

    58% {
        transform: translate(0, 10px) rotate(0)
    }

    60% {
        transform: translate(0, 8px) rotate(0)
    }

    62% {
        transform: translate(0, -3px) rotate(0)
    }

    64% {
        transform: translate(0, 4px) rotate(0)
    }

    66% {
        transform: translate(0, -8px) rotate(0)
    }

    68% {
        transform: translate(0, -6px) rotate(0)
    }

    70% {
        transform: translate(0, -8px) rotate(0)
    }

    72% {
        transform: translate(0, 7px) rotate(0)
    }

    74% {
        transform: translate(0, 7px) rotate(0)
    }

    76% {
        transform: translate(0, -6px) rotate(0)
    }

    78% {
        transform: translate(0, -8px) rotate(0)
    }

    80% {
        transform: translate(0, -6px) rotate(0)
    }

    82% {
        transform: translate(0, -1px) rotate(0)
    }

    84% {
        transform: translate(0, 10px) rotate(0)
    }

    86% {
        transform: translate(0, 10px) rotate(0)
    }

    88% {
        transform: translate(0, -8px) rotate(0)
    }

    90% {
        transform: translate(0, 1px) rotate(0)
    }

    92% {
        transform: translate(0, 9px) rotate(0)
    }

    94% {
        transform: translate(0, 4px) rotate(0)
    }

    96% {
        transform: translate(0, 1px) rotate(0)
    }

    98% {
        transform: translate(0, 7px) rotate(0)
    }

    0%,100% {
        transform: translate(0, 0) rotate(0)
    }
}
.rshare-qzone {
    display: block;
    width: 36px;
    height: 36px;
    border-radius: 50%;
    background-color: #ffffff;
    background-image: url('https://img.jbzj.com/skin/2018/images/share-icons.png');
    background-repeat: no-repeat;
    background-position: -3px -50px;
    border: 1px solid red;
    line-height: 36px;
    transition: .4s;
    -webkit-transition: .4s;
    &:hover {
      background-color: #ffa709;
      background-position: -48px -50px;
    }
}
.hvr-bubble-top {
    display: inline-block;
    vertical-align: middle;
    -webkit-transform: perspective(1px) translateZ(0);
    transform: perspective(1px) translateZ(0);
    box-shadow: 0 0 1px rgba(0, 0, 0, 0);
    position: relative;
}
[class^="hvr-"] {
    margin: .4em;
    padding: 1em;
    cursor: pointer;
    background: #e1e1e1;
    text-decoration: none;
    color: #666;
    -webkit-tap-highlight-color: rgba(0,0,0,0);
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
.hvr-bubble-top:hover:before, .hvr-bubble-top:focus:before, .hvr-bubble-top:active:before {
    -webkit-transform: translateY(-10px);
    transform: translateY(-10px);
}
.hvr-bubble-top:before {
    pointer-events: none;
    position: absolute;
    z-index: -1;
    content: '';
    border-style: solid;
    -webkit-transition-duration: 0.3s;
    transition-duration: 0.3s;
    -webkit-transition-property: transform;
    transition-property: transform;
    left: calc(50% - 10px);
    top: 0;
    border-width: 0 10px 10px 10px;
    border-color: transparent transparent #e1e1e1 transparent;
}
.hvr-bubble-float-top {
    display: inline-block;
    vertical-align: middle;
    -webkit-transform: perspective(1px) translateZ(0);
    transform: perspective(1px) translateZ(0);
    box-shadow: 0 0 1px rgba(0, 0, 0, 0);
    position: relative;
    -webkit-transition-duration: 0.3s;
    transition-duration: 0.3s;
    -webkit-transition-property: transform;
    transition-property: transform;
}
.hvr-bubble-float-top:hover, .hvr-bubble-float-top:focus, .hvr-bubble-float-top:active {
    -webkit-transform: translateY(10px);
    transform: translateY(10px);
}
.hvr-bubble-float-top:before {
    position: absolute;
    z-index: -1;
    content: '';
    left: calc(50% - 10px);
    top: 0;
    border-style: solid;
    border-width: 0 10px 10px 10px;
    border-color: transparent transparent #e1e1e1 transparent;
    -webkit-transition-duration: 0.3s;
    transition-duration: 0.3s;
    -webkit-transition-property: transform;
    transition-property: transform;
}
.hvr-bubble-float-top:hover:before, .hvr-bubble-float-top:focus:before, .hvr-bubble-float-top:active:before {
    -webkit-transform: translateY(-10px);
    transform: translateY(-10px);
}
.hvr-curl-top-left {
    display: inline-block;
    vertical-align: middle;
    -webkit-transform: perspective(1px) translateZ(0);
    transform: perspective(1px) translateZ(0);
    box-shadow: 0 0 1px rgba(0, 0, 0, 0);
    position: relative;
}
.hvr-curl-top-left:before {
    pointer-events: none;
    position: absolute;
    content: '';
    height: 0;
    width: 0;
    top: 0;
    left: 0;
    background: white;
    background: linear-gradient(135deg, white 45%, #aaa 50%, #ccc 56%, white 80%);
    filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr='#ffffff', endColorstr='#000000');
    z-index: 1000;
    box-shadow: 1px 1px 1px rgba(0, 0, 0, 0.4);
    -webkit-transition-duration: 0.3s;
    transition-duration: 0.3s;
    -webkit-transition-property: width, height;
    transition-property: width, height;
}
.hvr-curl-top-left:hover:before, .hvr-curl-top-left:focus:before, .hvr-curl-top-left:active:before {
    width: 25px;
    height: 25px;
}
.hvr-curl-top-left:before {
    pointer-events: none;
    position: absolute;
    content: '';
    height: 0;
    width: 0;
    top: 0;
    left: 0;
    background: white;
    background: linear-gradient(135deg, white 45%, #aaa 50%, #ccc 56%, white 80%);
    filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr='#ffffff', endColorstr='#000000');
    z-index: 1000;
    box-shadow: 1px 1px 1px rgba(0, 0, 0, 0.4);
    -webkit-transition-duration: 0.3s;
    transition-duration: 0.3s;
    -webkit-transition-property: width, height;
    transition-property: width, height;
}
</style>
